language: minimal

before_install:
    - make env

script:
    - make test
    - make build

deploy:
  provider: pypi
  username: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  edge: true # opt in to dpl v2
