language: minimal

before_install:
    - make env

stages:
    - name:
        - Test
        - Build

jobs:
    - stage: Tests
      name: "Test :skin: option"
      script:
        - source env/conda/bin/activate sphinxcontrib-verilog-diagrams
        - cd tests && python3 -m unittest test.TestSkins

    - stage: Tests
      name: "Test :yosys_script: option"
      script:
        - source env/conda/bin/activate sphinxcontrib-verilog-diagrams
        - cd tests && python3 -m unittest test.TestYosysScript

    - stage: Build
      name: "Build"
      script:
        - make build

before_deploy:
    - make clean
    - make sphinxcontrib_verilog_diagrams/version.py
    - sudo ln -sf /usr/bin/python3 /usr/bin/python

deploy:
  provider: pypi
  username: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  edge: true # opt in to dpl v2
