name: sphinxcontrib-verilog-diagrams
channels:
- symbiflow
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
- yosys
- graphviz      # Needed for dot
- nodejs
- netlistsvg
- pip:          # Packages installed from PyPI
  - -r file:requirements.txt
  - -r file:docs/requirements.txt
  - .
