name: v2x-docs
channels:
- symbiflow
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
- yosys
- nodejs
- pip:                            # Packages installed from PyPI
  - -r file:requirements.txt
